AES.c
const size_t AES_BLOCK_SIZE
Variable- const size_t AES_BLOCK_SIZE. Used to dictate the length in bytes of a single AES block used for encryption and decryption. Set to 16 bytes for a single block.
Variable - AES_BLOCK_SIZE - specifies the length per AES block - 16 bytes.
Referenced by AESEncrypt, AESDecrypt, RijndaelKeySchedule, ShiftRows, invShiftRows, getRoundKey, validatePlainTextLength, validateCipherTextLength, printAESBlock, IVHexToAscii, cbcEncryptFile, cbcDecryptFile, cbcEncrypt, cbcDecrypt, ecbEncrypt, ecbDecrypt, ecbEncryptFile, ecbDecryptFile.
size_t VERBOSE
Variable- size_t VERBOSE Used to dictate whether verbose output is printed to the terminal or not. If 0, does not print verbose. If 1, prints verbose.
Variable - VERBOSE - specifies if verbose output should be printed or not.
Referenced by AESEncrypt, AESDecrypt, cbcEncryptFile, cbcDecryptFile, cbcEncrypt, cbcDecrypt, cfbEncryptFile, cfbDecryptFile, cfbEncrypt, cfbDecrypt, ecbEncryptFile, ecbDecryptFile.
const unsigned char sbox[256][256]
const unsigned char sbox. Lookup table for the sbox values used during AES Encryption.
Referenced by getSBoxValue.
const unsigned char invSBox[256][256]
const unsigned char invSBox. Lookup table for the inverse sbox values used during AES Decryption.
Referenced by getInvSBox.
const unsigned char Rcon[255][255]
const unsigned char Rcon. Lookup table for the Rcon values used during Rijndael Key Schedule during the AES Encryption and Decryption.
Referenced by getRconValue.
int getNumRounds(int keyLength)
getNumRounds - Function to return the number of rounds of AES encryption and decryption based off of the length of the key given in
keyLength. keyLength - int - indicates the length of the key int - the number of rounds based off of the length of the key passed in the parameter keyLength. If the length of the key is not valid, returns -1.
Referenced by AESEncrypt, AESDecrypt, RijndaelKeySchedule, keyHexToAscii, main, cbcEncryptFile, cbcDecryptFile, cbcEncrypt, cbcDecrypt, cfbEncryptFile, cfbDecryptFile, cfbEncrypt, cfbDecrypt, ecbEncrypt, ecbDecrypt, ecbEncryptFile, ecbDecryptFile.
unsigned char getSBoxValue(unsigned char index)
getSBoxValue - Function to return the sBox value passed in as a parameter
index. Requires the original value required in hex. index - unsigned char - hexadecimal representation of the index for which the SBox value is required. unsigned char - sBox value for the paramter index.
References sbox.
Referenced by RijndaelKeySchedule, KeyScheduleCore, subBytes, main.
unsigned char getInvSBox(unsigned char index)
getInvSBox - Function to return the inverse sBox value passed in as a parameter
index. Requires the original value required in hex. index - unsigned char - hexadecimal representation of the index for which the inverse SBox value is required. unsigned char - inverse sBox value for the paramter index.
References invSBox.
Referenced by invSubBytes, main.
unsigned char getRconValue(unsigned char num)
getRconValue - Function to return the Rcon value for the index passed in as a parameter
num. Requires the original value required in hex. index - unsigned char - hexadecimal representation of the number for which the Rcon value is required during the key schedule. unsigned char - rCon value for the paramter num.
References Rcon.
Referenced by KeyScheduleCore.
int getPaddedKeyLength(int currentKeyLength)
getPaddedKeyLength - Function to return a valid key length (in bytes) based off of the current key length passed in as
currentKeyLength. Corresponds to minimum and maximum key length required for AES encryption and decryption. The key will then be padded to the length of the value returned from this function. If the keylength is less than 16, will return 16. If greater than 16, but less than 24, will return 24. If greater than 32, will return -1. currentKeyLength - int - current key length in bytes, to be padded to the return value int - the length in bytes that the key should be padded to.
Referenced by AESEncrypt, AESDecrypt, keyHexToAscii, cbcEncryptFile, cbcDecryptFile, cbcEncrypt, cbcDecrypt, cfbEncryptFile, cfbDecryptFile, cfbEncrypt, cfbDecrypt, ecbEncrypt, ecbDecrypt, ecbEncryptFile, ecbDecryptFile.
unsigned char* AESEncrypt(unsigned char *plainText, unsigned char *key, int plainTextLength, int keyLength)
AESEncrypt - Function to encrypt a single block of plaintext passed in as parameter plainText using AES encryption, for 128, 192 and 256 bit keys. Validates the keylength and returns the corresponding ciphertext. The caller of the function must ensure that the returned ciphertext pointer is freed. The ciphertext returned is always 16 bytes and the plainText must be 16 bytes or less. Makes use of zero padding. All input must be in ASCII and NOT hex.
char - unsigned char* plainText - pointer to the plaintext that needs to be encrypted using AES encryption. char - unsigned char* key - reference to the key that must be used for AES encryption. plainTextLength - length of the plaintext in plainText to be encrypted. keyLength - length of the key passed in as key used for the AES encryption. unsigned* char - Ciphertext resulting from the encryption of the plaintext passed in as plainText.
References VERBOSE, getPaddedKeyLength, getNumRounds, validateNumRounds, validatePlainTextLength, AES_BLOCK_SIZE, constructStateArray, printStateArray, RijndaelKeySchedule, getRoundKey, AddRoundKey, subBytes, ShiftRows, mixColumns, printAESBlock.
Referenced by main, cbcEncryptFile, cbcEncrypt, cfbEncryptFile, cfbDecryptFile, cfbEncrypt, cfbDecrypt, ecbEcryptHelper, ecbEncryptFile.
unsigned char* AESDecrypt(unsigned char *cipherText, unsigned char *key, int cipherTextLength, int keyLength)
AESDecrypt - Function to decrypt a single block of ciphertext passed in as parameter cipherText using AES decryption, for 128, 192 and 256 bit keys. Validates the keylength and returns the corresponding plaintext. The caller of the function must ensure that the returned plaintext pointer is freed. The plaintext returned is always 16 bytes and the plainText must be 16 bytes or less. Makes use of zero padding. All input must be in ASCII and NOT hex.
char - unsigned char* cipherText - pointer to the ciphertext that needs to be decrypted using AES decryption. char - unsigned char* key - reference to the key that must be used for AES decryption. cipherTextLength - length of the ciphertext in cipherText to be decrypted. keyLength - length of the key passed in as key used for the AES decryption. unsigned* char - Plaintext resulting from the decryption of the ciphertext passed in as cipherText.
References VERBOSE, getPaddedKeyLength, getNumRounds, validateNumRounds, validateCipherTextLength, AES_BLOCK_SIZE, constructStateArray, printStateArray, RijndaelKeySchedule, getRoundKey, AddRoundKey, invShiftRows, invSubBytes, invMixColumns, printAESBlock.
Referenced by main, cbcDecryptFile, cbcDecrypt, ecbDecryptHelper, ecbDecryptFile.
unsigned char* RijndaelKeySchedule(unsigned char *originalKey, int keyLength)
RijndaelKeySchedule - Function that performs the Rijndael key scheduling for AES encryption. Takes in the original key passed in as parameter.
originalKey and the length of the original key given as parameter. The caller must free the memory allocated and returned. originalKey - unsigned char * - An unsigned char pointer to the original key. keyLength - int - length of originalKey passed in as a parameter originalKey expandedKey - The key that has been expanded.
References getNumRounds, validateNumRounds, AES_BLOCK_SIZE, KeyScheduleCore, getSBoxValue.
Referenced by AESEncrypt, AESDecrypt, main.
void KeyScheduleCore(unsigned char *word, int wordLength, int rConIterationVal)
KeyScheduleCore - Function that performs the key schedule core for the Rijndael Key Schedule. Performs a single rotate left of the word passed in as.
word and applies the required s-box substituion and rcon XOR. char - unsigned char* word - pointer to the word onto which the key schedule core should be operated. wordLength - length of the word passed in as a parameter word. rConIterationVal - the iteration value to be used for the rcon XOR.
References SingleRotateLeft, getSBoxValue, getRconValue.
Referenced by RijndaelKeySchedule.
void SingleRotateLeft(unsigned char *word, int wordLength)
SingleRotateLeft - Function to rotate the array passed in as a paramter.
word a single time left (8 bits to the left), with the left most element becoming the right most element. As such: rotate(1d2c3a4f) = 2c3a4f1d. word - unsigned char *word - the array/word to be left rotated by 8 bits. wordLength - int - length of the parameter word.
Referenced by KeyScheduleCore, ShiftRows.
void printStateArray(uint8_t stateArray[4][4])
printStateArray - Function to print the state array to the terminal in hex format.
stateArray - the state array that should be printed to the terminal.
Referenced by AESEncrypt, AESDecrypt.
void AddRoundKey(unsigned char state[4][4], unsigned char key[4][4])
AddRoundKey - Function that performs the Bitwise XOR between state and key as per AES encryption.
state - unsigned char - is the current state of the ciphertext or plaintext during AES encryption or decryption key - unsigned char - sub key to be added for the current round to the current state vector
Referenced by AESEncrypt, AESDecrypt, main.
void mixColumns(unsigned char state[4][4])
mixColumns - Function that performs the MixColumns step of AES as specified by AES encryption.
state - unsigned char - is the current state of the ciphertext or plaintext during AES encryption or decryption
Referenced by AESEncrypt, main.
void invMixColumns(unsigned char state[4][4])
invMixColumns - Function that does the inverse of the Mix Column Step for AES Encryption. Performs the gallois field multiplication and the required XOR to the state passed in as a paramter
state. state - unsigned char - is the current state of the ciphertext or plaintext during AES encryption or decryption.
References galloisFieldMult.
Referenced by AESDecrypt, main.
unsigned char galloisFieldMult(unsigned char a, unsigned char b)
galloisFieldMult - Function to perform the Galois field multiplication operation required for the inverse mix columns and the mix columns operation of the AES encryption and decryption processes. Returns the result of the multiplication.
a - first character to perform Galois field multiplication. b - second character to perform Galois field multiplication. unsigned char - Result of the Galois field multiplication.
Referenced by invMixColumns.
void subBytes(unsigned char state[4][4])
subBytes - Function that performs the sub byte operation where each value is replaced by the s box value
state - unsigned char - is the current state of the ciphertext or plaintext during AES encryption or decryption.
References getSBoxValue.
Referenced by AESEncrypt, main.
void invSubBytes(unsigned char state[4][4])
invSubBytes - Function that performs the inverse of Function subBytes
state - unsigned char - is the current state of the ciphertext or plaintext during AES encryption or decryption
References getInvSBox.
Referenced by AESDecrypt.
void ShiftRows(unsigned char state[4][4], int wordLength)
ShiftRows - Function to shift the state array according to the AES encryption standard for 128 - bits blocks.
state - unsigned char - is the current state of the ciphertext or plaintext during AES encryption or decryption
References AES_BLOCK_SIZE, SingleRotateLeft.
Referenced by AESEncrypt, main.
void invShiftRows(unsigned char state[4][4], int wordLength)
invShiftRows - Function to shift the state array Inverse according to the AES encryption standard for 128 - bits blocks
state - unsigned char - is the current state of the ciphertext or plaintext during AES encryption or decryption
References AES_BLOCK_SIZE, SingleRotateRight.
Referenced by AESDecrypt, main.
void SingleRotateRight(unsigned char *word, int wordLength)
SingleRotateRight - Function to rotate the array passed in as a paramter.
word a single time right (8 bits to the right), with the right most element becoming the left most element. As such: rotate(1d2c3a4f) = 4f1d2c3a. word - unsigned char *word - the array/word to be right rotated by 8 bits. wordLength - int - length of the parameter word.
Referenced by invShiftRows.
void getRoundKey(unsigned char *expandedKey, unsigned char *roundKey, int roundNum)
getRoundKey - Function to extract the correct sub-key to use for the appropriate round specified by
roundNum. Copies the sub-key from the expanded key in expandedKey to roundKey. char - expandedKey - The expanded key from which to extract the sub-key. char - roundKey - memory to which to copy the sub-key. roundNum - int - the round number for which the sub-key is required.
References AES_BLOCK_SIZE.
Referenced by AESEncrypt, AESDecrypt.
void constructStateArray(unsigned char *flatArray, unsigned char stateArray[][4])
constructStateArray - Function to convert the state array from a flat 1D array to a multidimensional array.
char flatArray -the 1D array to be converted. stateArray - the multidimensional array to which to copy the flat array elements to.
Referenced by AESEncrypt, AESDecrypt.
uint8_t hexToInt(char ch)
hexToInt - Function that converts a given hex value into an integer.
ch - hex value that wil be converted to int. uint8_t the converted int value.
Referenced by hexToAscii.
uint8_t hexToAscii(char ch1, char ch2)
hexToAscii - Function that converts a given hex value to its ASCII equivalent.
ch1 - char value of the first hex value. ch2 - char value of the second hex value.
References hexToInt.
Referenced by hexToAsciiString.
void hexToAsciiString(char *hexString, char *asciiString, int hexStringLength)
hexToAsciiString - Function that converts a given string of hex values into its ASCII equivalent. A hex string contains hex chars and is "encoded" in ascii In order to encrypt it, it must be converted to the equivalent ascii plain text string plaintext string is half the size of hex, since two hex chars = 1 ascii char if hex string is "4A" it will be converted to "J" in ascii which will have a hex representation of "4a" The original hex string converted to hex staright or printed in hex straight rather will print or have the value "0x34", "0x31" BASICALLY THE HEX STRING FF IS INTERPRETED AS THE CHARS FF, whereas when using this function we intend it to be "J", ie the char "J"
char* hexString - The string of hex values to be converted. char* asciiString - The output of the converted hex string. int hexStringLength - The length of parameter hexString.
References hexToAscii.
Referenced by keyHexToAscii, IVHexToAscii, main, cbcEncryptFile, cbcDecryptFile, cbcEncrypt, cbcDecrypt, cfbEncryptFile, cfbDecryptFile, cfbEncrypt, cfbDecrypt, ecbEncrypt, ecbDecrypt, ecbEncryptFile, ecbDecryptFile.
unsigned char* asciiToHexString(unsigned char *asciiString, unsigned char *hexString, size_t asciiStringLen)
Function name: asciiToHexString - convert an ascii String to an ascii string.
asciiString - unsigned char* pointing to the ASCII String to be converted. hexString - unsigned char* pointing to a memory where the converted Hex string should be stored. asciiStringLen - size_t containing the length of the ASCII String to be converted. unsigned char* asciiToHexString - pointer to the converted Hex String, pointing to the same memory location as hexString.
Referenced by cbcDecryptFile, cfbDecryptFile, ecbDecryptFile.
void validateNumRounds(int numRounds, int keyLength)
validateNumRounds - Function that validates the number of rounds that have been passed in by the
numRounds. Upon invalid validation, relevent error information will be printed to terminal and the program will exit with an EXIT_FAILURE flag. numRounds - int - Integer value of the number rounds
Referenced by AESEncrypt, AESDecrypt, RijndaelKeySchedule, cbcEncryptFile, cbcDecryptFile, cbcEncrypt, cbcDecrypt, cfbEncryptFile, cfbDecryptFile, cfbEncrypt, cfbDecrypt, ecbEncrypt, ecbDecrypt, ecbEncryptFile, ecbDecryptFile.
void validatePlainTextLength(size_t plainTextLength)
validatePlainTextLength - Function that validates the length of the plaintext. The validation is done against the AES_BLOCK_SIZE value
plainTextLength - int - The length of the plaintext text as an integer value
References AES_BLOCK_SIZE.
Referenced by AESEncrypt.
void validateCipherTextLength(int cipherTextLength)
validateCipherTextLength - Function that validates the length of the ciphertext. The validation is done against the AES_BLOCK_SIZE value
cipherTextLength - int - The length of the cipher text as an integer value
References AES_BLOCK_SIZE.
Referenced by AESDecrypt.
void printAESBlock(unsigned char *block)
printAESBlock - Function to print a single block in hex format to the terminal.
block - block to be printed.
References AES_BLOCK_SIZE.
Referenced by AESEncrypt, AESDecrypt, cbcEncryptFile, cbcDecryptFile, cbcEncrypt, cbcDecrypt, cfbDecryptFile, ecbEcryptHelper, ecbDecryptHelper, ecbEncryptFile, ecbDecryptFile.
int fileNameDirIndex(char *fileName, int fileNameLength)
Returns the last index of '/' in a given path, otherwise returns -1 if no '/' is found.
fileName The path to a file fileNameLength The length of the provided file int Index of the last '/' in the path, else -1 if no '/' was found
Referenced by getOutputFileName.
void stripDirectory(char *fileName, char *extractedFileName, char *extractedFilePath, int fileNameLength, int slashIndex)
Removes path from the provided path to a file and returns only the file name.
stripDirectory - Function that removes path from the provided path to a file and returns only the file name fileName The path to a specified file extractedFileName The name of the file within the provided path to a file extractedFilePath The path to file, excluding the file name fileNameLength The length of the paramter fileName slashIndex The index of the last '/' in the original file path passed in as a paramter fileName
Referenced by getOutputFileName.
void getOutputFileName(int type, char *fileName, char *outputFileName, char *mode)
Get the output file name from all the parameters passed in.
type 0 - Encrypt, 1 - Decrypt fileName The name of the input file outputFileName The name of the output file mode Chipher mode to be used (ECB, CBC, CFB)
References fileNameDirIndex, stripDirectory.
Referenced by cbcEncryptFile, cbcDecryptFile, cfbEncryptFile, cfbDecryptFile, ecbEncryptFile, ecbDecryptFile.
uint8_t isFileTxt(unsigned char *fileName)
isFileTxt - Function to determine if the file passed in as a paramter
filename is a text file with extension .txt or not. Returns a 1 if it is and a 0 if it isn't. fileName - unsigned char* fileName - path to file to determine if the file is a text file or not. uint8_t - boolean indicating if it is a text file or not. (0 is not a text file, 1 is a text file)
Referenced by cbcDecryptFile, cfbDecryptFile, ecbDecryptFile.
unsigned char* keyHexToAscii(unsigned char *hexKey, int keyLength)
keyHexToAscii - Function to convert a key from a Hex string passed in as a paramter
hexKey to an ascii string. User must free the returned pointer to memory allocated. Returns the Ascii equivalent. The caller must free the pointer returned. char - unsigned char* hexKey - hex representation of the key to be converted to ASCII. keyLength - length of the hex representation of the key passed in as paramter hexKey. unsigned* - the ASCII representation of the hex key passed in as parameter hexKey.
References getNumRounds, getPaddedKeyLength, hexToAsciiString.
Referenced by cbcEncryptFile, cbcDecryptFile, cbcEncrypt, cbcDecrypt, cfbEncryptFile, cfbDecryptFile, cfbEncrypt, cfbDecrypt, ecbEncrypt, ecbDecrypt, ecbEncryptFile, ecbDecryptFile.
unsigned char* IVHexToAscii(unsigned char *hexIV, int IVLength)
IVHexToAscii - Function to convert a initialization vector from a Hex string passed in as a paramter.
hexIV to an ascii string. User must free the returned pointer to memory allocated. Returns the Ascii equivalent. The caller must free the pointer returned. char - unsigned char* hexIV - hex representation IVLength - length of the hex representation of the IV passed in as paramter hexIV. unsigned* - the ASCII representation of the hex IV passed in as parameter hexIV.
References AES_BLOCK_SIZE, hexToAsciiString.
Referenced by cbcEncryptFile, cbcDecryptFile, cbcEncrypt, cbcDecrypt, cfbEncryptFile, cfbDecryptFile, cfbEncrypt, cfbDecrypt.
unsigned char* XORBlocks(unsigned char *block1, unsigned char *block2, int length)
XORBlocks - Function to XOR two blocks of length.
length and retuns the XOR'd result. User must free the memory returned. char - block1 - First block to be XOR'd. char - block2 - Second block to be XOR'd. length - length of the blocks to be XOR'd. unsigned* - Result of the XOR.
Referenced by cbcEncryptFile, cbcDecryptFile, cbcEncrypt, cbcDecrypt, cfbEncryptFile, cfbDecryptFile, cfbEncrypt, cfbDecrypt.